### PR TITLE
Added methods to get data in list.

### PR DESCRIPTION
**Pull request by haseeb-heaven**
Added GetCountryList(),GetPopulationList(),GetProvinceList(),GetCountyList() with source as "jhu" by default.

### CODE REVIEW

**Comment by haseeb-heaven** [comment]
> You forgot the R in GetCountryList()

What does 'R' refers to ?

**Comment by Abdirahiim** [comment]
You accidentally wrote County instead of Country

**Comment by haseeb-heaven** [comment]
> You accidentally wrote County instead of Country

There are two different methods GetCountryList() and GetCountyList() dont get confused

**Comment by Abdirahiim** [comment]
My bad, I forgot about the csbs source 😅

**Pull request merged**
